#=
SEXSGE.jl — a hand-written stand-in for a PowerSystems-generated component struct.

IMPORTANT:
In a real contribution this file would be AUTO-GENERATED by PowerSystems from a JSON
descriptor (see `src/models/generated/` in PowerSystems.jl). You would edit the descriptor
and run the code generator; you would never hand-edit a generated file. For this tutorial we
write the struct by hand so the whole model lives in a script and needs no PowerSystems
rebuild — but the *shape* below (fields, the four "Do not modify" bookkeeping fields, and the
flat list of getters/setters) is exactly what the generator produces.

Assumes the including scope defines `const PSY = PowerSystems` (or `import PowerSystems as PSY`).
=#

"""
    mutable struct SEXSGE <: PSY.AVR

GE Simplified Excitation System (SEXS_GE). Relative to `SEXS` it adds:
  * a voltage transducer lag `Tr`           -> state `Vm`
  * a PI block `Kc (1 + s Tc) / (s Tc)`      -> state `Vi`
  * a separate field-voltage output limit `Efd_lim`

States (all differential): `Vm, Vr, Vi, Vf`.
"""
mutable struct SEXSGE <: PSY.AVR
    "Ratio of lead and lag time constants, Ta/Tb"
    Ta_Tb::Float64
    "Lag time constant, Tb (s)"
    Tb::Float64
    "Regulator gain, K"
    K::Float64
    "Field circuit time constant, Te (s)"
    Te::Float64
    "Voltage transducer time constant, Tr (s)"
    Tr::Float64
    "PI proportional gain, Kc"
    Kc::Float64
    "PI integral time constant, Tc (s)"
    Tc::Float64
    "Regulator (internal) voltage limits (Emin, Emax)"
    V_lim::PSY.MinMax
    "Field voltage output limits (Efd_min, Efd_max)"
    Efd_lim::PSY.MinMax
    "Reference voltage set-point (pu)"
    V_ref::Float64
    "An extra dictionary for user metadata not used in simulation."
    ext::Dict{String, Any}
    "(**Do not modify.**) The states are: Vm, Vr, Vi, Vf"
    states::Vector{Symbol}
    "(**Do not modify.**) SEXSGE has 4 states"
    n_states::Int
    "(**Do not modify.**) SEXSGE has 4 differential states"
    states_types::Vector{PSY.StateTypes}
    "(**Do not modify.**) PowerSystems.jl internal reference"
    internal::PSY.InfrastructureSystemsInternal
end

# Positional constructor: fills the bookkeeping fields the generator would fill.
function SEXSGE(
    Ta_Tb,
    Tb,
    K,
    Te,
    Tr,
    Kc,
    Tc,
    V_lim,
    Efd_lim,
    V_ref = 1.0,
    ext = Dict{String, Any}(),
)
    return SEXSGE(
        Ta_Tb,
        Tb,
        K,
        Te,
        Tr,
        Kc,
        Tc,
        V_lim,
        Efd_lim,
        V_ref,
        ext,
        [:Vm, :Vr, :Vi, :Vf],
        4,
        [
            PSY.StateTypes.Differential,
            PSY.StateTypes.Differential,
            PSY.StateTypes.Differential,
            PSY.StateTypes.Differential,
        ],
        PSY.InfrastructureSystemsInternal(),
    )
end

# Keyword constructor (the form users actually call).
function SEXSGE(;
    Ta_Tb,
    Tb,
    K,
    Te,
    Tr,
    Kc,
    Tc,
    V_lim,
    Efd_lim,
    V_ref = 1.0,
    ext = Dict{String, Any}(),
)
    return SEXSGE(Ta_Tb, Tb, K, Te, Tr, Kc, Tc, V_lim, Efd_lim, V_ref, ext)
end

#=
Interface getters required by PowerSystems / PSID machinery.
These EXTEND the PowerSystems functions (PSID calls `PSY.get_states`, `PSY.get_n_states`,
etc. internally when it builds the device wrapper), so they must live on `PSY.*`.
=#
PSY.get_states(value::SEXSGE) = value.states
PSY.get_n_states(value::SEXSGE) = value.n_states
PSY.get_states_types(value::SEXSGE) = value.states_types
PSY.get_internal(value::SEXSGE) = value.internal
PSY.get_ext(value::SEXSGE) = value.ext
PSY.get_V_ref(value::SEXSGE) = value.V_ref
PSY.set_V_ref!(value::SEXSGE, val) = value.V_ref = val

#=
Parameter getters consumed by the SEXSGE dynamics methods (mass matrix, ODE, init).
Defined as plain functions in the including scope (the script does NOT `using PowerSystems`,
so these names are free). In the real generated file they would be `PSY.get_*`.
=#
get_Ta_Tb(value::SEXSGE) = value.Ta_Tb
get_Tb(value::SEXSGE) = value.Tb
get_K(value::SEXSGE) = value.K
get_Te(value::SEXSGE) = value.Te
get_Tr(value::SEXSGE) = value.Tr
get_Kc(value::SEXSGE) = value.Kc
get_Tc(value::SEXSGE) = value.Tc
get_V_lim(value::SEXSGE) = value.V_lim
get_Efd_lim(value::SEXSGE) = value.Efd_lim
